---
title: "test2"
author: "Owen Dy"
date: "2024-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(httr)
library(dplyr)
library(shiny)
library(stringr)
library(tidyr)
library(ggplot2)
library(chron)
library(scales)
library(lubridate)
library(bigchess)

```

```{r}

chess_username <- "owej9023"
desired_rows<-10000000
# Replace 'your_api_url_here' with the actual API endpoint for retrieving user data
api_url <- paste0("https://api.chess.com/pub/player/",chess_username,"/games/archives")

# Make a GET request to the API
response <- GET(api_url)


# Get the content of the response
response_content <- content(response, "text")

# Parse the JSON content
archives <- jsonlite::fromJSON(response_content)

# Initialize an empty list to store dataframes
dataframes <- list()
#print(archives)
# Loop through each archive URL and retrieve the data
archive_data<-list()
for (url in archives$archives) {
  archive_response <- GET(url)
  archive_content <- content(archive_response, "text", flatten = TRUE)
  archive_data1 <- jsonlite::fromJSON(archive_content)
  archive_data <- c(archive_data,archive_data1)

}

result_list <- list()
archive_data <- archive_data[sapply(archive_data, is.list)]


combined_df <- bind_rows(archive_data)


combined_df <- combined_df %>% filter(grepl("Blitz", time_class, ignore.case = TRUE))

filtered_data <- combined_df %>% filter(rules == "chess")
filtered_data <- filtered_data %>% filter(rated == "TRUE")

# Assuming filtered_data$pgn is a vector of PGN games
for (game in filtered_data$pgn) {
  
  # Concatenate the lines of the game
  input_text <- paste(game, collapse = " ")
  
  # Use regex to extract values within square brackets
  matches <- str_extract_all(input_text, "\\[(.*?)\\]")[[1]][1:21]
  
  # Store the result in the list
  result_list <- c(result_list, list(matches))
}

#for (game in filtered_data$pgn)

# Convert the list to a data frame
result_df <- do.call(rbind, result_list)
result_df <- as.data.frame(result_df)
result_df<-na.omit(result_df)
# Shrink the dataframe to the desired number of rows
if (desired_rows >= length(result_df$game_number)){
  result_df <- tail(result_df, desired_rows)
}
for (i in seq_along(result_df[, 3])) {
  # Extract the date string from the format "[Date "2020.12.08"]"
  date_string <- gsub("\\[Date \"|\"\\]", "", result_df[i, 3])
  
  # Convert the extracted value to a Date object
  #formatted_date <- as.Date(date_string, format = "%Y.%m.%d")
  
  # Replace the original value with the formatted date
  result_df[i, 3] <- date_string
}

for (i in seq_along(result_df[, 7])) {
  # Extract the result string from the format '[Result "0-1"]' or '[Result "1/2-1/2"]'
  result_string <- as.character(result_df[i, 7])
  
  # Extract the result using a modified regular expression
  result_match <- regmatches(result_string, regexpr("\\d+/\\d+-\\d+/\\d+|\\d+-\\d+", result_string))[[1]]
  
  # Replace the original value with the extracted result
  result_df[i, 7] <- result_match
}


for (i in seq_along(result_df[, 14])) {
  # Extract the Elo rating string from the format '[BlackElo "845"]'
  elo_string <- as.character(result_df[i, 14])
  
  # Extract all numeric values using regular expression
  elo_matches <- regmatches(elo_string, gregexpr("\\d+", elo_string))[[1]]
  
  # Convert the extracted values to numeric
  elo_numeric <- as.numeric(elo_matches)
  
  # Replace the original value with the numeric Elo rating(s)
  result_df[i, 14] <- elo_numeric
}

for (i in seq_along(result_df[, 15])) {
  # Extract the Elo rating string from the format '[BlackElo "845"]'
  elo_string <- as.character(result_df[i, 15])
  
  # Extract all numeric values using regular expression
  elo_matches <- regmatches(elo_string, gregexpr("\\d+", elo_string))[[1]]
  
  # Convert the extracted values to numeric
  elo_numeric <- as.numeric(elo_matches)
  
  # Replace the original value with the numeric Elo rating(s)
  result_df[i, 15] <- elo_numeric
}

# Assuming result_df is your data frame
for (i in seq_along(result_df[, 16])) {
  time <- as.character(result_df[i, 16])
  
  # Extract numeric values using regular expression
  times_numeric <- as.numeric(gsub("\\D", "", time))
  
  # Replace the original value with the numeric time(s)
  result_df[i, 16] <- times_numeric
}

result_df$V18 <- as.character(result_df$V18)

for (i in seq_along(result_df[, 18])) {
  time_string <- as.character(result_df[i, 18])
  
  # Extract time using regular expression
  time_matches <- regmatches(time_string, regexpr("\\d{2}:\\d{2}:\\d{2}", time_string))[[1]]
  
  # Replace the original value with the numeric time
  result_df[i, 18] <- time_matches
}


# Assuming result_df is your data frame
for (i in seq_along(result_df[, 20])) {
  time_string <- as.character(result_df[i, 20])
  
  # Extract time using regular expression
  time_matches <- regmatches(time_string, regexpr("\\d{2}:\\d{2}:\\d{2}", time_string))[[1]]
  
  # Replace the original value with the numeric time
  result_df[i, 20] <- time_matches
}

for (i in seq_along(result_df[, 5])) {
  user_string <- as.character(result_df[i, 5])
  
  # Extract username using regular expression
  extracted_user <- sub("\\[.*?\"(.*?)\"\\]", "\\1", user_string)
  
  # Replace the original value with the extracted username
  result_df[i, 5] <- extracted_user
}

for (i in seq_along(result_df[, 6])) {
  user_string <- as.character(result_df[i, 6])
  
  # Extract username using regular expression
  extracted_user <- sub("\\[.*?\"(.*?)\"\\]", "\\1", user_string)
  
  # Replace the original value with the extracted username
  result_df[i, 6] <- extracted_user
}

result_df <- as.data.frame(result_df)
result_df$V3 <- as.Date(result_df$V3, format = "%Y.%m.%d")

result_df$day_of_week <- weekdays(result_df$V3)
result_df$day_of_week <- factor(result_df$day_of_week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

# Remove columns V17 and V21
result_df <- result_df %>%
  select(-V17, -V21)

# Mutate the dataframe to create the chess_username column
result_df <- result_df %>%
  rowwise() %>%
  mutate(
    chess_username = ifelse(chess_username %in% c(V5, V6), as.numeric(ifelse(chess_username %in% V5, V14, V15)), NA_real_)
  )



# Convert the column to numeric if needed
result_df$chess_username <- as.numeric(result_df$chess_username)

# Convert 'V14' to numeric (assuming it contains numeric values)
result_df$V14 <- as.numeric(result_df$V14)
result_df$V15 <- as.numeric(result_df$V15)
result_df$V16 <- as.numeric(result_df$V16)

# Convert 'V18' to character
# Convert 'V18' to hms object

result_df$V18 <- as.character(result_df$V18)
result_df$V18 <- hms(result_df$V18)
result_df$V18 <- replace_na(result_df$V18, hms("00:00:00"))

result_df$V20 <- as.character(result_df$V20)
result_df$V20 <- hms(result_df$V20)
result_df$V20 <- replace_na(result_df$V20, hms("00:00:00"))

# Extract the hour from the datetime column
result_df$hour <- hour(result_df$V18)
result_df$hourend <- hour(result_df$V20)
result_df$game_number <- 1:nrow(result_df)


recent_games_data <- result_df

recent_games_data_games_per_day <- recent_games_data %>%
  group_by(V3) %>%
  mutate(
    total_change_elo = sum(chess_username - lag(chess_username, default = first(chess_username))),
    total_games_per_day = n(),
    group_id = ceiling(row_number() / 10)
  ) %>%
  ungroup()

summary_data <- recent_games_data_games_per_day %>%
  group_by(day_of_week) %>%
  summarize(
    mean_elo_change = mean(total_change_elo),
    sd_elo_change = sd(total_change_elo),
    count = n()
  )

# Calculate standard error of the mean (SEM) for Elo change
summary_data$sem_elo_change <- summary_data$sd_elo_change / sqrt(summary_data$count)


# Create a new column for the week number
recent_games_data$week_number <- as.numeric(format(as.Date(recent_games_data$V3), "%U"))

# Aggregate by week
summary_data_week <- recent_games_data %>%
  group_by(week_number) %>%
  summarize(
    mean_eweek_elo = mean(chess_username),  # Change to your actual column name
    sd_eweek_elo = sd(chess_username),  # Change to your actual column name
    count = n()
  )

# Calculate standard error of the mean (SEM) for each week
summary_data_week$sem_eweek_elo <- summary_data_week$sd_eweek_elo / sqrt(summary_data_week$count)



# Assuming you have a date column called date_column (replace it with your actual column name)
# Create a new column for the month
recent_games_data$month <- factor(format(as.Date(recent_games_data$V3), "%B"), 
                                  levels = month.name, ordered = TRUE)

# Aggregate by month
summary_data_month <- recent_games_data %>%
  group_by(month) %>%
  summarize(
    mean_emon_elo = mean(chess_username),  # Change to your actual column name
    sd_emon_elo = sd(chess_username),  # Change to your actual column name
    count = n()
  )

# Calculate standard error of the mean (SEM) for each month
summary_data_month$sem_emon_elo <- summary_data_month$sd_emon_elo / sqrt(summary_data_month$count)


```

```{r}
# Initialize variables
incriment <- FALSE
selectedIncriment <- 0

# Loop through each value in the 'time_control' column of 'combined_df'
for (value in combined_df$time_control) {
  # Split the string based on the '+'
  split_strings <- strsplit(value, "\\+")[[1]]
  
  if (length(split_strings) == 2) {
    # If there are two values, set 'incriment' to TRUE and 'selectedIncriment' to the second value
    incriment <- TRUE
    selectedIncriment <- as.numeric(split_strings[2])
  } else {
    # If there is only one value, set 'incriment' to FALSE and use a default incriment of 0
    incriment <- FALSE
    selectedIncriment <- 0
  }

  # Extract the length of the game for each player in minutes
  Length_of_Game_For_Each_Player <- as.numeric(split_strings[1])
  
  # Convert minutes to HH:MM format
  time_in_hhmm <- sprintf("%02d:%02d", Length_of_Game_For_Each_Player[1] %/% 60, Length_of_Game_For_Each_Player[1] %% 60)
  
  # Set 'set_value' to the formatted time
  set_value <- time_in_hhmm
}

# Ignore daily games for the analysis of time spent per move

# Initialize an empty list before the loop
result_list_times <- list()

# Loop through each game in the 'filtered_data$pgn'
for (game in filtered_data$pgn) {
  # Concatenate the lines of the game
  input_text <- paste(game, collapse = " ")
  
  # Use regex to extract values within square brackets
  matches <- str_extract_all(input_text, "\\{[^\\}]*\\}")

  # Process each match and add a comma after each match
  processed_matches <- lapply(matches[[1]], function(match) {
    gsub("}", "},", match)
  })

  # Store the result in the list
  result_list_times <- append(result_list_times, list(processed_matches))
}


# Create a function that calculates the amount of time spent per move
subtract_time <- function(set_value, variable) {
  set_time <- as.POSIXct(set_value, format = "%M:%OS")
  set_time <- as.numeric(set_time)
  variable_time <- as.POSIXct(variable, format = "%M:%OS")
  variable_time <- as.numeric(variable_time)
  # Subtract the variable time from the set time
  result_time <- set_time - variable_time

  # Return the result time
  return(result_time)
}

```

```{r,echo=FALSE, hide = TRUE}
timepermove<-list()
count <- 0
for (value in combined_df$time_control) {
  # Split the string based on the '+'
  split_strings <- strsplit(value, "\\+")[[1]]

  # Extract the length of the game for each player in minutes
  Length_of_Game_For_Each_Player <- as.numeric(split_strings[1])
  
  # Convert minutes to HH:MM format
  time_in_hhmm <- sprintf("%02d:%02d", Length_of_Game_For_Each_Player[1] %/% 60, Length_of_Game_For_Each_Player[1] %% 60)
  
  # Set 'set_value' to the formatted time
  set_value <- time_in_hhmm
  
  # Initialize a list to store time per move within the outer loop
  timepermoveinterior <- list()  
  # Extract all matches of time values in the 'value'
  count<-count +1
  matches <- str_extract_all(filtered_data$pgn[count], '\\d+\\d+:\\d+(?:\\.\\d+|)]')
  matches<-str_extract_all(matches,'\\d+:\\d+(?:\\.\\d+|)')
  set_value<-set_value
  set_value1<-set_value
  
  
  for (move in 1:length(matches[[1]])){
    if(move %% 2 == 0){
      m2 <- as.character(matches[[1]][move])
      # Convert the string to POSIXct format (minutes and seconds)
      NewMatches <- as.POSIXct(m2, format = "%M:%OS")
      # Calculate time remaining using a custom function 'subtract_time'
      timeRemaining <- subtract_time(set_value, NewMatches)
      # Update 'set_value' for the next iteration
      set_value <- m2
      # Round the time remaining to one decimal place and add it to the interior list
      timeRemaining <- round(timeRemaining, digits = 1)
      timepermoveinterior<-c(timepermoveinterior,timeRemaining)

    }
    else{
      if (move == 1){
        m1 <- set_value1
      }
      else{
        m1 <- as.character(matches[[1]][move])
      }
      # Convert the string to POSIXct format (minutes and seconds)
      NewMatches1 <- as.POSIXct(m1, format = "%M:%OS")
      # Calculate time remaining using a custom function 'subtract_time'
      timeRemaining <- subtract_time(set_value1, NewMatches1)
      # Update 'set_value' for the next iteration
      set_value1 <- m1
    
      # Round the time remaining to one decimal place and add it to the interior list
      timeRemaining <- round(timeRemaining, digits = 1)
      timepermoveinterior<-c(timepermoveinterior,timeRemaining)

    }
    #timepermoveinterior<-c(timepermoveinterior,timeRemaining)
    #print(timepermoveinterior)

  }

  timepermove <- c(timepermove, list(timepermoveinterior))
}
```
```{r}
#filtered_data2<-filtered_data$pgn
#filtered_data2
```




```{r}

zzz <- do.call(rbind, lapply(seq_along(timepermove), function(list_num) {
  inner_list <- timepermove[[list_num]]
  if(length(inner_list) > 0) {
    df <- as.data.frame(do.call(rbind, inner_list))
    df$move_number <- seq_along(df[[1]])
    df$game_number <- list_num
    return(df)
  } else {
    return(NULL)
  }
}))


pgndataonly <- as.character(filtered_data$pgn)  # Convert PGN data to character vector
writeLines(pgndataonly, "filtered_data2.pgn")  # Write PGN data to file

#test
```

```{r}
#ggplot(data = zzz)+aes(V1,move_number)+geom_col()
ggplot(data = zzz) + 
  aes(x = V1, y = (..count..)/sum(..count..)) +
  geom_bar(stat="count", fill="blue") +
  scale_y_continuous(labels=scales::percent_format(scale=1)) +
  xlim(0,20) +
  ylab("Percentage") +
  xlab("Time Spent Per Move (Seconds)")

ggplot(data = zzz) + 
  aes(x = move_number, y = (..count..)/sum(..count..)) +
  geom_bar(stat="count", fill="red") +
  scale_y_continuous(labels=scales::percent_format(scale=1))+
  ylab("Percentage")

```
```{r}
filtered_data<-filtered_data
library(DBI)
mydb <- dbConnect(RSQLite::SQLite(), "ChessDatabase.sqlite")
dbDisconnect(mydb)

mydb <- dbConnect(RSQLite::SQLite(), "")
dbWriteTable(mydb, "zzz", zzz)
#dbWriteTable(mydb, "filtered_data", filtered_data)
dbListTables(mydb)
dbGetQuery(mydb, 'SELECT * FROM zzz LIMIT 5')

```

```{r}
# Initialize variables
count <- 0
whitetimepermove <- list()
blacktimepermove <- list()
blackcount <- 0

# Loop through each element in the 'timepermove' list
for (i in 1:length(timepermove)) {
  
  # Extract the first move for each color from the game
  Value1 <- as.numeric(timepermove[[i]][2])
  Value2 <- as.numeric(timepermove[[i]][1])
  # Get the individual list of time per move
  individualList <- timepermove[[i]]
  whitetime <- list()
  blacktime <- list()
  
  # Loop through each move in the individual list
  for (j in seq_along(individualList)) {
    count <- count + 1
    value <- as.numeric(individualList[j])
    # Check if it's a black move (count is even)
    if (count %% 2 == 0) {
      if (value != Value2){
        blacktime<-c(blacktime,value)
        # get black move
        blackcount <- blackcount + 1
      }

    } 
    if (count %% 2 == 1) {
      if (value != Value2){
        #print(value)
        # get white move
        whitetime <- c(whitetime, value)       
      }
    }
  }
  
  # Append the individual lists to the main lists
  blacktimepermove <- append(blacktimepermove, list(blacktime))
  whitetimepermove <- append(whitetimepermove, list(whitetime))
}

# The code processes a list of time per move in a chess game,
# separating white and black moves and calculating time differences.
# The results are stored in 'whitetimepermove' and 'blacktimepermove' lists.
# 'blackcount' keeps track of the number of black moves.

```
